platform :ios, '7.0'
inhibit_all_warnings!

target 'TestCircleCi' do
  pod 'ReactiveCocoa', '2.5'
  pod 'SVProgressHUD', '2.0.3'
  pod 'SVPullToRefresh', '0.4.1'
  pod 'Bolts', '1.8.4'
  pod 'Masonry', '1.0.2'
  pod 'KTCenterFlowLayout', '1.3.1'
  pod 'RestKit', '0.26.0'
  pod 'UICKeyChainStore', '2.1.0'
  pod 'BlocksKit', '2.2.5'
  pod 'UITextView+Placeholder', '1.2.0'
  pod 'DateTools', '1.7.0'
  pod 'SDWebImage', '3.8.2'
  pod 'VTAcknowledgementsViewController', '1.2'
  pod 'MWPhotoBrowser', '2.1.2'
  pod 'GoogleAnalytics', '3.17.0'
  pod 'Fabric', '1.6.11'
  pod 'Crashlytics', '3.8.3'
  pod 'FTPopOverMenu', '1.2.2'
end
